In [2]:
import pandas as pd
import os
import shutil
import csv

In [9]:
df = pd.read_csv('access_log.20220801.csv',encoding='utf-8')
df['Datetime'] = pd.to_datetime(df['Datetime'],format = '[%d/%b/%Y:%H:%M:%S%z]')
df.rename(columns={'Unknown Client ID':'Unknown'},inplace=True)
df

,IP,Remote Log Name,User Identifier,Datetime,Request,Requested URL,Status Code,Size,Referrer,User Agent,Unknown
0,66.249.79.219,-,-,2022-08-01 09:00:00+09:00,"""GET/att_photo/news/1504190225_170831233705.jp...",http://www.lafent.com/att_photo/news/150419022...,304,255,"""-""","""Googlebot-Image/1.0""",False
1,114.111.32.86,-,-,2022-08-01 09:00:01+09:00,"""GET/jobse/news_list.html?st=D&page=3&ci=&cb=0...",http://www.lafent.com/jobse/news_list.html?st=...,200,83634,"""-""","""Mozilla/5.0(compatible;Yeti/1.1;+https://nave...",False
2,-,-,-,2022-08-01 09:00:01+09:00,"""GET/index_mk.php HTTP/1.1""",http://www.lafent.com/index_mk.php,200,69667,"""-""","""Wget/1.14(linux-gnu)""",False
3,110.93.150.31,-,-,2022-08-01 09:00:07+09:00,"""GET/jobse/news_list.html?st=D&page=6&ci=&cb=0...",http://www.lafent.com/jobse/news_list.html?st=...,200,83400,"""-""","""Mozilla/5.0(compatible;Yeti/1.1;+https://nave...",False
4,173.252.83.17,-,-,2022-08-01 09:00:07+09:00,"""GET/mbweb/news/view.html?news_id=131046 HTTP/...",http://www.lafent.com/mbweb/news/view.html?new...,200,95241,"""-""","""facebookexternalhit/1.1(+http://www.facebook....",False
...,...,...,...,...,...,...,...,...,...,...,...
214764,157.90.177.228,-,-,2022-08-02 08:59:54+09:00,"""GET/inews/news_list.html?mcd=A01&cb=06&cs=10&...",http://www.lafent.com/inews/news_list.html?mcd...,200,91899,"""-""","""Mozilla/5.0(compatible;BLEXBot/1.0;+http://we...",False
214765,114.119.136.72,-,-,2022-08-02 08:59:55+09:00,"""GET/photo/photo_list.html?mcd=C01&ctf=25&cts=...",http://www.lafent.com/photo/photo_list.html?mc...,200,70354,"""http://www.lafent.com/photo/photo_list.html?m...","""Mozilla/5.0(Linux;Android7.0;)AppleWebKit/537...",False
214766,211.249.246.114,-,-,2022-08-02 08:59:55+09:00,"""GET/inews/news_list.html?mcd=H21&ci=08&cb=09&...",http://www.lafent.com/inews/news_list.html?mcd...,200,82380,"""-""","""Mozilla/5.0(compatible;Daum/4.1;+http://cs.da...",False
214767,-,-,-,2022-08-02 08:59:58+09:00,"""GET/data/banner/1641881889jpg HTTP/1.0""",http://www.lafent.com/data/banner/1641881889jpg,200,21506,"""-""","""-""",False
214768,-,-,-,2022-08-02 08:59:58+09:00,"""GET/data/banner/1655711454gif HTTP/1.0""",http://www.lafent.com/data/banner/1655711454gif,200,76905,"""-""","""-""",False

In [8]:
df.rename(columns={'Unknown Client ID':'Unknown'},inplace=True)
df

,IP,Remote Log Name,User Identifier,Datetime,Request,Requested URL,Status Code,Size,Referrer,User Agent,Unknown
0,66.249.79.219,-,-,2022-08-01 09:00:00+09:00,"""GET/att_photo/news/1504190225_170831233705.jp...",http://www.lafent.com/att_photo/news/150419022...,304,255,"""-""","""Googlebot-Image/1.0""",False
1,114.111.32.86,-,-,2022-08-01 09:00:01+09:00,"""GET/jobse/news_list.html?st=D&page=3&ci=&cb=0...",http://www.lafent.com/jobse/news_list.html?st=...,200,83634,"""-""","""Mozilla/5.0(compatible;Yeti/1.1;+https://nave...",False
2,-,-,-,2022-08-01 09:00:01+09:00,"""GET/index_mk.php HTTP/1.1""",http://www.lafent.com/index_mk.php,200,69667,"""-""","""Wget/1.14(linux-gnu)""",False
3,110.93.150.31,-,-,2022-08-01 09:00:07+09:00,"""GET/jobse/news_list.html?st=D&page=6&ci=&cb=0...",http://www.lafent.com/jobse/news_list.html?st=...,200,83400,"""-""","""Mozilla/5.0(compatible;Yeti/1.1;+https://nave...",False
4,173.252.83.17,-,-,2022-08-01 09:00:07+09:00,"""GET/mbweb/news/view.html?news_id=131046 HTTP/...",http://www.lafent.com/mbweb/news/view.html?new...,200,95241,"""-""","""facebookexternalhit/1.1(+http://www.facebook....",False
...,...,...,...,...,...,...,...,...,...,...,...
214764,157.90.177.228,-,-,2022-08-02 08:59:54+09:00,"""GET/inews/news_list.html?mcd=A01&cb=06&cs=10&...",http://www.lafent.com/inews/news_list.html?mcd...,200,91899,"""-""","""Mozilla/5.0(compatible;BLEXBot/1.0;+http://we...",False
214765,114.119.136.72,-,-,2022-08-02 08:59:55+09:00,"""GET/photo/photo_list.html?mcd=C01&ctf=25&cts=...",http://www.lafent.com/photo/photo_list.html?mc...,200,70354,"""http://www.lafent.com/photo/photo_list.html?m...","""Mozilla/5.0(Linux;Android7.0;)AppleWebKit/537...",False
214766,211.249.246.114,-,-,2022-08-02 08:59:55+09:00,"""GET/inews/news_list.html?mcd=H21&ci=08&cb=09&...",http://www.lafent.com/inews/news_list.html?mcd...,200,82380,"""-""","""Mozilla/5.0(compatible;Daum/4.1;+http://cs.da...",False
214767,-,-,-,2022-08-02 08:59:58+09:00,"""GET/data/banner/1641881889jpg HTTP/1.0""",http://www.lafent.com/data/banner/1641881889jpg,200,21506,"""-""","""-""",False
214768,-,-,-,2022-08-02 08:59:58+09:00,"""GET/data/banner/1655711454gif HTTP/1.0""",http://www.lafent.com/data/banner/1655711454gif,200,76905,"""-""","""-""",False

In [5]:
csvs = [f for f in os.listdir() if '.csv' in f.lower()]

os.mkdir('csv_files')

for csv in csvs:
    df = pd.read_csv(csv,encoding='utf-8')
    df['Datetime'] = pd.to_datetime(df['Datetime'],format = '[%d/%b/%Y:%H:%M:%S%z]')
    df.rename(columns={'Unknown Client ID':'Unknown'},inplace=True)
    df.to_csv(csv,encoding='utf-8')
    new_path = 'csv_files/' + csv
    shutil.move(csv, new_path)

C:\Users\wesleyquest\AppData\Local\Temp\ipykernel_10928\4085655379.py:6: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv,encoding='utf-8')
C:\Users\wesleyquest\AppData\Local\Temp\ipykernel_10928\4085655379.py:6: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv,encoding='utf-8')
C:\Users\wesleyquest\AppData\Local\Temp\ipykernel_10928\4085655379.py:6: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv,encoding='utf-8')
C:\Users\wesleyquest\AppData\Local\Temp\ipykernel_10928\4085655379.py:6: DtypeWarning: Columns (6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv,encoding='utf-8')
C:\Users\wesleyquest\AppData\Local\Temp\ipykernel_10928\4085655379.py:6: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv,encoding='utf-8')
C:\Users\wesleyquest\AppData\Local\Temp\ipykernel_10928\4085655379.py:6: DtypeWarning: Columns (6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv,encoding='utf-8')
C:\Users\wesleyquest\AppData\Local\Temp\ipykernel_10928\4085655379.py:6: DtypeWarning: Columns (6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv,encoding='utf-8')
C:\Users\wesleyquest\AppData\Local\Temp\ipykernel_10928\4085655379.py:6: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv,encoding='utf-8')
C:\Users\wesleyquest\AppData\Local\Temp\ipykernel_10928\4085655379.py:6: DtypeWarning: Columns (6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv,encoding='utf-8')
C:\Users\wesleyquest\AppData\Local\Temp\ipykernel_10928\4085655379.py:6: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv,encoding='utf-8')
C:\Users\wesleyquest\AppData\Local\Temp\ipykernel_10928\4085655379.py:6: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv,encoding='utf-8')
C:\Users\wesleyquest\AppData\Local\Temp\ipykernel_10928\4085655379.py:6: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv,encoding='utf-8')
C:\Users\wesleyquest\AppData\Local\Temp\ipykernel_10928\4085655379.py:6: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv,encoding='utf-8')

ValueError: time data "p.ro.to.t.ypezpx.h@c.h.ai.ra.dm.i.t.q.l.h.r@j.o.R.N.S.Tory@jo.hnsdfsdff.dsgdsgdshdghsdhdhfd@j.o.r.n.s.tory@jo.hnsdfsdff.dsgdsgdshdghsdhdhfd@pa.r.a.j.ump.e.rs.jas.s.e.n.20.14@mob.I.l.ityqens@Go.o.gle.email.2.1@Sus.ta.i.n.j.ex.k@p.e.ll.dewangk.aoyumugute.ngxun@Gal.EHi.Nt.on78.8.27@dfu.s.m.f.h.u8.645v.nb@WWW.EMEKAOLISA@carlton.theis@silvia.woodw.o.r.t.h@s.jd.u.eh.yds.g.524.87.59.68.4@johnsdfsdff.dsgdsgdshdghsdhdhfd@M.a.na.gement.Xz.u.y@oliver.thompson@johndf.gfjhfgjf.ghfdjfhjhjhjfdgh@sybbr>r.eces.si.v.e.x.g.z@leanna.langton@c.o.nne.c.t.tn.tu@Go.o.gle.email.2.\\\\\\\\\\\\\\\\n1@sarahjohnsonw.estbrookbertrew.e.r@hu.fe.ng.k.Ua.ngniu.bi..uk41@Www.Zanele@silvia.woodw.o.r.t.h@veda.lafferty@s.m.it.hwangkangfengyufeng@hu.fen.gk.uang.ni.u.b.i.xn-.u.k.6.2@jo.Hnsdfsdff.dsgdsgdshdghsdhdhfd@r.eces.si.v.e.x.g.z@leanna.langton[24/Nov/2022:14:49:08" doesn't match format "[%d/%b/%Y:%H:%M:%S%z]", at position 11509. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [ ]:
for csv in csvs:
    os.remove(csv)

In [ ]:
keys = ['IP','Remote Log Name','User Identifier','Datetime','Request','Requested URL','Status Code','Size','Referrer','User Agent']
with open('access_log.2208-2302.csv','w',encoding='utf-8') as f:
    dict_writer = csv.DictWriter(f,keys)
    dict_writer.writeheader()